let nombre = "Cristóbal"
let apellido = 'Subires'
let estudiante = nombre.concat(' ', apellido)
let estudianteMayus = estudiante.toUpperCase()
let estudianteMinus = estudiante.toLowerCase()
let longitud = estudiante.length
let primera_letra = nombre.charAt(0)
let ultima_letra = apellido.charAt(apellido.length-1)
let eliminar = estudiante.replace("estudiante")
let existe = estudiante.includes(nombre)